### ISSUE TITLE
force specify IP for SNI

### ISSUE THREAD

**Issue by s0i37** [maurosoria/dirsearch#1053]
### What is the feature?

`dirsearch.py -u http://old.domain.com/ --ip '1.2.3.4'`   <- ok, will not resolve old.domain.com

`dirsearch.py -u https://old.domain.com/ --ip '1.2.3.4' -b`   <- will try to resolve old.domain.com

### What is the use case?

It needs for discovering old sites which domains was removed.

When and who will use this? Why this matters?

It is absolutely useless for CTF and very matters for real life.

**Comment by shelld3v** [comment]
I don't really understand what do you want here. If you want to brute force old.domain.com knowing their IP address already (maybe the DNS record is now removed but you saved its IP before), you can try `dirsearch.py -u http://old.domain.com/ --ip '1.2.3.4'`

**Comment by s0i37** [comment]
`dirsearch.py -u http://old.domain.com/ --ip '1.2.3.4'`   - it is without SNI
but if I want with SNI I make:
`dirsearch.py -u https://old.domain.com/ --ip '1.2.3.4' -b`  - in this case dirseach make dns-request
For example ffuf does it right:
`ffuf -u "https://1.2.3.4:443/FUZZ" -sni "target.com"`

**Comment by maurosoria** [comment]
@s0i37 and @shelld3v how you doing?

I understand why this feature could be important (specially when the front-webserver requires SNI, and maybe you're trying to bruteforce another internal server)

I've looked if there is a way to do this with python-requests, but haven't found a way yet (I should read requests source code maybe...)

But mostly sure there is a way because requests is built on top of urllib3 and the last one supports it:
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#custom-sni-hostname

Give us some time and we'll probably can find a way (with an argument like -force-sni)

**Comment by shelld3v** [comment]
@maurosoria Actually #1046 will solve this

**Comment by shelld3v** [comment]
@maurosoria Actually #1046 will solve this

**Comment by shelld3v** [comment]
@maurosoria Actually #1046 will solve this
