### ISSUE TITLE
Cannot run dirsearch in macbook pro m1 terminal

### ISSUE THREAD

**Issue by AzhariRamadhan** [maurosoria/dirsearch#1190]
azhariramadhan@MacBook-Pro-Azhari dirsearch % python3 dirsearch.py --url https://evil.com/

  _|. _ _  _  _  _ _|_    v0.4.2.8
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 25
Wordlist size: 11458

Output File: /Users/azhariramadhan/dirsearch/reports/https_evilcom/__22-09-05_20-18-02.txt

Target: https://evil.com/

[20:18:02] Starting: 

Task Completed
azhariramadhan@MacBook-Pro-Azhari

**Comment by euzada** [comment]
Hi I test it again on Windows terminal (Ubuntu) and got the same bug: no result in terminal. 

So, I test it again using --log option to see the output results in a separate file, it works. I have all the results including all the GET with 200, 301, 404, ... status. I believe the issue is the terminal should show the 200 status directly filtered but this is not the case. 
[results.txt](https://github.com/maurosoria/dirsearch/files/9497258/results.txt)

Please see the resukts.txt file for the output results of the log option. The 200 status is what I fount working in the past on some users that shared a screenShot of their terminal like the one at the following adress:

https://1.bp.blogspot.com/-nbMC5di29To/YCgGMWoo-kI/AAAAAAAAtsc/68Bz7w28AYAFPUkDazB24Uy2jdpJolXawCLcBGAsYHQ/s16000/1.png

I hope this will help solve it.

**Comment by AzhariRamadhan** [comment]
@euzada not solve, no result in report, still empty

**Comment by shelld3v** [comment]
Hi, the bugs haven't been fixed yet, please be patient

**Comment by euzada** [comment]
> @euzada not solve, no result in report, still empty

I didn't say it is solved. I said the log file will have all the results but the output in terminal still has issues.

**Comment by euzada** [comment]
It's working now. thank you.
