### ISSUE TITLE
Output multiple reports

### ISSUE THREAD

**Issue by p3stR** [maurosoria/dirsearch#1286]
### What is the feature?

Output the scan results in multiple report types at the same scan not by executing the scan multiple times and change the report type.

### What is the use case?

Have the results on different formats

**Comment by nrathaus** [comment]
To support this feature we would need to fix:
1. option `output` (under `setup_reports(self)`)
2. option `output_format` (under `setup_reports(self)`)

I think best option is to create a `dict` named `output_medium` with two variables `output` and `output_format`

Make the incoming `output` and `output_format` values comma separated and broken down and parsed - then saved into this new `output_medium` which will be now used instead of `output` and `output_format` variables throughout the code and iterated over and the information sent out accordingly
