### ISSUE TITLE
Some errors in readme

### ISSUE THREAD

**Issue by AMG4MATIC** [maurosoria/dirsearch#1294]
### What is the current behavior?

In the Options part, the flag is --exclude-text, --exclude-regexp
But in the Filter part, the flag is --exclude-texts, --exclude-regexps
### What is the expected behavior?

What it should be instead?
 the Filter part should change the flag to --exclude-text, --exclude-regexp
### Any additional information?

<img width="805" alt="image" src="https://user-images.githubusercontent.com/47023007/228714188-b3479f27-8baa-4e9e-9924-e1be77babc61.png">

**Comment by Prady18** [comment]
@AMG4MATIC The expected behavior would be to update the flag names in the Filter part to match those in the Options part. Specifically, the flag names in the Filter part should be changed to "--exclude-text" and "--exclude-regexp" to align with the flag names used in the Options part.

To solve the error, you would need to update the flag names in the Filter part of the software or tool to match the correct flag names "--exclude-text" and "--exclude-regexp". This can typically be done by modifying the code or configuration settings related to the Filter functionality in the software or tool to reflect the correct flag names.

**Comment by AMG4MATIC** [comment]
Sorry for not explaining clearly. What I meant is that there is a small error in the README file, and only updating the README file is needed.

**Comment by Prady18** [comment]
ok update
