### ISSUE TITLE
features - add an action for website's error

### ISSUE THREAD

**Issue by myalcin81** [maurosoria/dirsearch#190]
Hello,
When dirsearch filled with a couple 400-404 errors, It's waiting for action, Is it possible to add a flag for action What could be that. 
Example;
-Flag -werror=*, Variables;
-1 skip and continue,
-2 stop and cancel the search,
-3 wait for user action[default]

**Comment by maurosoria** [comment]
Can you explain better?

**Comment by myalcin81** [comment]
Simplified, When dirsearch got 400-404 response status from the target host, we should able to automate the action with additional flag/arg. to proceed. as a command example;
dirsearch  -error-pages-action: 1

Recommended actions:
-1 skip and continue,
-2 stop and cancel the search,
-3 wait for user action[Default - Current behavior]

**Comment by shelld3v** [comment]
I don't think about an argument like that, but will try to create the *stop and cancel the search* option!

**Comment by myalcin81** [comment]
the point is on there, control the search when you got 404s. In my case I don't want to stop or cancel the process.

thank you

**Comment by shelld3v** [comment]
Thanks, I will do something LIKE this soon!

**Comment by shelld3v** [comment]
@myalcin81 What do you think about the new 429 detection feature? I have thought again and decided not to create this, because status codes are the results of the endpoints, there is no reason why we should do this and this when hitting 403, this is a scanner to find those things, or filter those things to find other things. We should only do something when the response shows that there is a problem in the server, the scan is gonna be useless. We have an option to stop on the server error and pause when hitting 429, that is enough!

I will think again if you can give an example (a real use case)!

**Comment by myalcin81** [comment]
@shelld3v hey, I haven't tested the latest features yet. I didn't mention forcing the tool to scan while you are getting 429 responses from useless websites. 
My request was about configuring the tool for the next action of HTTP status codes, and it seems capable of doing it well now. I will let you know after review it.
Thanks. I think we can close the issue. Further feedbacks should be opened in a new thread.

**Comment by shelld3v** [comment]
>My request was about configuring the tool for the next action of HTTP status codes, and it seems capable of doing it well now.

I haven't created your feature yet, because it's seemed not useful in my opinion! I am creating other detections for some specific status codes, like 429!

**Comment by shelld3v** [comment]
I think you misunderstood my comment. I mean, I created the 429 detection feature (v0.4.1) + I decided not to create something like what you said (actions by status codes)!
