### ISSUE TITLE
Removed db files?

### ISSUE THREAD

**Issue by jonaslejon** [maurosoria/dirsearch#26]
Is the db/dirbuster/ and other files in the db-directory been removed?

**Comment by maurosoria** [comment]
Yes, I've removed them because they were too big (slow downloading/cloning).

Anyway, you can still get them from this commit: https://github.com/maurosoria/dirsearch/tree/db29b6fe2201b6e9f5c50f707cb4b93f1c985ab6/db

I'm collecting different dictionaries in order to open a different repository with them (with a few scripts for joining/modifying them). So all suggestions/submits are welcome.

**Comment by jonaslejon** [comment]
Ok. Thanks for the info!
