### ISSUE TITLE
It only finds directories with code 301.

### ISSUE THREAD

**Issue by Be1nna** [maurosoria/dirsearch#482]
He doesn't find indexes 400 and 200.

**Comment by shelld3v** [comment]
Hi, I don't understand the question! Also, who is "he"? Do you mean "dirsearch"?

**Comment by Be1nna** [comment]
The directories it found are not correct. (Does not open.)

**Comment by shelld3v** [comment]
It will be a challenge for me to can understand what are you trying to talking about. 

First, *directories are opened*, there is no definition about what is an open directory, an example map for server-side files and folders is something like this:

```
|
|___folder1
|       |___ sub-folder1
|             |___ file1.php
|             |___ file2.html
|       |___ sub-folder2
|             |___ sub-folder3
|             |___ file3.conf
|___folder2
       |___ file4.txt
       |___ file5.md
```

If you want to say that directories found by dirsearch don't exist, then you should know that you can't just visit `/folder/`, you need to know the files in that folder, and it will be something like this: `/folder/file.php`. You can use the dirsearch `--recursive` flag for that.

Second, from an old comment:

>He doesn't find indexes 400 and 200.

Do you mean that dirsearch only shows endpoints return 301, ignore others? Then you are wrong, dirsearch will return everything that has the response code different from 404. Probably you haven't hit an endpoint like that yet so dirsearch doesn't print out, try a better wordlist 👍 

Since I don't know what do you want to ask, I just post everything here, hope if any of them can answer your question!

**Comment by Be1nna** [comment]
Thanks!
