### ISSUE TITLE
Misses bunch of 403s STATUS CODES

### ISSUE THREAD

**Issue by alexerxx** [maurosoria/dirsearch#603]
compared with ffuf and gobuster, misses most of 403 errors
![1](https://user-images.githubusercontent.com/74594219/99372755-88d9ca00-28b8-11eb-9689-c54983b03e4b.png)
![2](https://user-images.githubusercontent.com/74594219/99372758-8a0af700-28b8-11eb-8d57-14afb404b5d3.png)

**Comment by shelld3v** [comment]
Hi @alexerxx, this is the power of dirsearch. Dirsearch will send a test request to `.RANDOM_STRING` to test for calibration. If any path like `.STRING` that has the same response as the tested `.RANDOM_STRING`, it will be filtered. From that, you won't able to see  too many false positives anymore!

**Comment by shelld3v** [comment]
Sorry for the delay!!!

**Comment by shelld3v** [comment]
Hi, have that resolved your question? If yes, you can close this now! Feel free to ask any other question, there are a bunch of dirsearch secrets that can only see from the development side ;)

**Comment by alexerxx** [comment]
Hey thanks that's really nice, these screenshots I took while doing a ctf. But actually the problem occurred to me while I'm hitting a real site where it was possible to bypass .htpasswd (I don't remember) and it was missed by dirsearch.

**Comment by alexerxx** [comment]
Filtering is really good idea, is it for only [.] DOT's or filters any false positive responses /admin/ /adm!ns/. Thank you very much for your support

**Comment by shelld3v** [comment]
>But actually the problem occurred to me while I'm hitting a real site where it was possible to bypass .htpasswd (I don't remember) and it was missed by dirsearch.

I don't think so! Dirsearch only filter responses that have the SAME content length as the response from the test requests (`.RANDOM_VALUE`). If `.htpasswd` has the same response as `.hj2wj34hsuil`, then it will be filtered. And if `.HTpassWd` can bypass the Access Denied page, it will have a different response from `.hj2wj34hsuil` or `.htpasswd`, that won't be filtered

>Filtering is really good idea, is it for only [.] DOT's or filters any false positive responses /admin/ /adm!ns/

Our false positive tests now are: `RANDOM`, `.RANDOM`, `RANDOM/`, `RANDOM.<selected-extensions>` (`RANDOM.php`, `RANDOM.html`, ...). We don't want to add more because it will cause a longer delay before starting, that many users may think our tool is slow! 

A note that if endpoints with the `admin` keyword have been blocked but you still want to brute-force and believe that you can still able to access some endpoints with `admin`, you may need to filter responses with the `admin` endpoint. You can do this with `--calibration=admin`

We are keep updating to make this tool more perfect, thanks!

**Comment by shelld3v** [comment]
If we have answered your question, you can close this!
