### ISSUE TITLE
use `-e ~` leak own username and OS type to target

### ISSUE THREAD

**Issue by alqomar** [maurosoria/dirsearch#872]
**Current Behavior**
`-e` treat `~` as a command instead of a character
example :
`python3 dirsearch.py -u https://example.com -e ~ -f -b`
In Linux executed by dirsearch as
`python3 dirsearch.py -u https://example.com -e /home/username -f -b`

**Expected Behavior**
In my opinion all parameter inside `-e` should be treated as string/character to prevent accidentally polluted target server with own username
dirsearch `--suffixes ~` is a proper way to find backup files. But still, the `-e` behavior is unexpected i think.

**Software Version**
dirsearch v0.4.0
Python 3.9.2-3
OS : Debian Unstable
-  [x] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Hi, we have nothing to do with this. Do you know why this happens? It's because in Linux terminal environment, some special characters such as `~`, `*`, ... are system env variables. If you enter directly them in your command (without any way to determine it's a string, like quoting), those characters will be resolved to unintended values (it's intended, but unintended for people who don't know about it like you).

Solution: `python3 dirsearch.py -u https://example.com -e php --suffixes "~"`

**Comment by alqomar** [comment]
Your solution make me realize that i didn't test `--suffixes ~`, only read the tips 

> Want to find out config files or backups? Try --suffixes ~ and --prefixes .

That what make me confused, why `~` in `--suffixes ~` treated as char while in `-e ~` as a /home/username? It turned out that both treated `~` as a /home/username (in Linux).

You are right, i don't know about system env variables behaviour, how/why cli application can/can't manipulate that. Theres still some questions in my head, but let me ask search engine. Thank you for your time.

**Comment by shelld3v** [comment]
No problem
