### ISSUE TITLE
302 redirects not automatically added to the recursive queue

### ISSUE THREAD

**Issue by LywLover** [maurosoria/dirsearch#884]
### What is the current behavior?

302 redirects not automatically added to the recursive queue
![image](https://user-images.githubusercontent.com/29304484/120967946-c6416e80-c79a-11eb-9786-71518cef5b10.png)

![image](https://user-images.githubusercontent.com/29304484/120968655-b4140000-c79b-11eb-9d92-48fa1f22b435.png)

### Any additional information?
I tried
python3 dirsearch.py -u example.com -r
python3 dirsearch.py -u example.com -r --force-recursive --recursion-depth 3 --recursion-status 200-399,403

both not automatically added 302 redirects to the recursive queue
#### Checker:
 - [√ ] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
@LywLover Does the redirect (first pic) point to the same host with the same protocol? I mean, if `https://example.com/admin` sends you to `http://example.com/admin/`, it won't be added. And the redirect must follow a rule: `http://url/path1` must redirect to `http://url/path1/anythinghere` in order to be added to the queue, which is not followed by the second picture

**Comment by shelld3v** [comment]
I'm closing this now, feel free to ask for reopening
