### ISSUE TITLE
Path detection

### ISSUE THREAD

**Issue by Baikeryoyo** [maurosoria/dirsearch#945]
When I have a path http://xxx.com/test/a/
Command: dirsearch.py -u http://xxx.com/test/a/
The detection result using dirsearch is http://xxx.com/ instead of http://xxx.com/test/a/
I want to probe the path under /test/a/

**Comment by shelld3v** [comment]
>The detection result using dirsearch is http://xxx.com/ instead of http://xxx.com/test/a/

Why do you think that? Any screenshot?

**Comment by Baikeryoyo** [comment]
![image](https://user-images.githubusercontent.com/57838797/127822897-624fe4ab-8a46-4da3-9543-6ccb2b6c4ce0.png)
Here, my path is / # /, but actually it starts from XXX: 1890 /. I want to detect the path behind / # /

**Comment by shelld3v** [comment]
Hi, dirsearch can't brute-force after `#`, and brute-forcing after `#` is also absolutely useless, because everything after `#` (also called "hash") is used for client-side only, can be captured by client-side javascript for purposes but has no impact on the server response. More information here: https://en.wikipedia.org/wiki/URI_fragment
