### ISSUE TITLE
Reverse Recursive Scan

### ISSUE THREAD

**Issue by drego85** [maurosoria/dirsearch#981]
### What is the feature?

Following this [Issue](https://github.com/maurosoria/dirsearch/issues/980), I think it is useful to introduce a Reverse Recursive Scan!

### What is the use case?

If I scan this url: `https://www.example.org/downloads/documents/` dirsearch will automatically scan the previous directories. Example:

1. https://www.example.org/downloads/documents/
2. https://www.example.org/downloads/
3. https://www.example.org/

Thanks

**Comment by shelld3v** [comment]
It isn't a good or necessary feature, people can type 
`dirsearch -u https://www.example.org/ --subdir /,downloads,downloads/documents`
which doesn't take too much time to do

**Comment by shelld3v** [comment]
Therefore I'm closing this issue, thank you for your contribution and feel free to submit more ideas!

**Comment by drego85** [comment]
Really?

Three people have even put a like and is it necessary for you to close the idea/issue? 🤷‍♂️

I understand that you can manually indicate subdirectories, but automatically it would be more rapid!

/cc @maurosoria

**Comment by shelld3v** [comment]
I want to keep dirsearch options unique, special and really useful, `--subdirs` was actually made to achieve something you said above. If one day I can enhance dirsearch to UI app, I would add your suggested feature, but since dirsearch is a command-line tool, I want to ignore small and alternative features, which mostly focus on comfort, to focus on bigger things, cause I don't like to see a mess of non-sense features appear in the help message. I can see quite a number of people like this feature, so I will let @maurosoria decide.
