### ISSUE TITLE
Same pages back bugs

### ISSUE THREAD

**Issue by yanghaoi** [maurosoria/dirsearch#986]
When I scan a website,dirsearch output like this:
![image](https://user-images.githubusercontent.com/21354684/141425175-b21effab-6109-42d4-9a33-8d5d44b3ddea.png)

The website always return same pages .....  

Can we check html file md5 hash if the website always response same pages counts > 5 ?

**Comment by shelld3v** [comment]
@yanghaoi Hi, is it possible to disclose the target? Because checking html responses and filtering similar pages are something we have already done, so I might need to do more tests and investigations to point out the issue or improve our tool.
Also can you try to run the scan again with this command: `dirsearch.py -u <target> -t 10 --exclude-response php.bak`

**Comment by yanghaoi** [comment]
This target: https://meet.saicgmf.com/

**Comment by shelld3v** [comment]
Hi, you can try this: `./dirsearch.py -u https://meet.saicgmf.com/ --exclude-response '/php.old' -e php,html`

**Comment by yanghaoi** [comment]
Thanks, It's working...  ^_^
